services:
  - type: web
    name: portfolio-api
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    autoDeploy: true
    branch: main
    rootDir: backend
